### ISSUE TITLE
something funky is going on with the videoThumb variable (I think)

### ISSUE THREAD

**Issue by kmelve** [GitbookIO/plugin-youtube#2]
It's weird, but in the non-website versions, the same video thumbnail is used for all videos in the books, even though the links renders correctly. It's always the image for the last video in the book that is used for all. Is it something in how the pdf and epub generators works?

**Comment by SamyPesse** [comment]
Probably, which version are you using? I guess it's a problem when gitbook is downloading remote image, the last one probably override the others.

**Comment by kmelve** [comment]
I'm on the 2.0.0-alpha.6. You think the problem lies outside this plugin then?

**Comment by SamyPesse** [comment]
No, I think the problem is coming from here: https://github.com/GitbookIO/gitbook/blob/version/2.0/lib/utils/page.js#L124

since the filename of the url is `0;jpg` for all images.

**Comment by SamyPesse** [comment]
Ok the error was stupid, I will fix it right away.

**Comment by kmelve** [comment]
Cool. It would probably create trouble in other cases as well. Great to get it fixed though!

**Comment by SamyPesse** [comment]
I will publish a new version of gitbook soon (today or tomorrow).
